opt_out_usage

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the app"
  lane :build do
    run_tests(
      scheme: "SnapSafe",
      device: "iPhone 17",
      build_for_testing: true
    )
  end

  desc "Run unit tests"
  lane :test do
    run_tests(
      scheme: "SnapSafe",
      devices: ["iPhone 17"],
      only_testing: ["SnapSafeTests"]
    )
  end
  desc "Run tests on multiple iOS versions and device types"
  lane :run_multi_version_tests do
    # Test against latest and latest minus 1
    ios_versions = ['18.5', '26.0']

    device_types = [
      { name: 'iPhone 17', type: 'iPhone' },
    ]

    ios_versions.each do |version|
      device_types.each do |device|
        UI.message "Testing on #{device[:name]} with iOS #{version}..."

        run_tests(
          scheme: "SnapSafe",
          device: "#{device[:name]} (#{version})",
          only_testing: ["SnapSafeTests"],
          output_directory: ".fastlane/test_output/#{version.gsub('.', '_')}_#{device[:type]}"
        )
      end
    end
  end

  desc "Build release IPA"
  lane :build_release do
    gym(
      project: "SnapSafe.xcodeproj",
      scheme: "SnapSafe",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "SnapSafe.ipa",
      export_options: {
        provisioningProfiles: {
          "com.darkrockstudios.apps.snapsafe" => "SnapSafe Distribution"
        }
      }
    )
  end

  desc "Upload to TestFlight"
  lane :beta do
    gym(
      project: "SnapSafe.xcodeproj",
      scheme: "SnapSafe",
      export_method: "app-store"
    )

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build and upload to App Store Connect"
  lane :deploy do
    gym(
      project: "SnapSafe.xcodeproj",
      scheme: "SnapSafe",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.darkrockstudios.apps.snapsafe" => "SnapSafe Distribution"
        }
      }
    )

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true
    )

    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true,
      submit_for_review: false,
      force: false
    )
  end
end
